display_name: eqTrainer
icon: linux/assets/app_icon.png
summary: A beautiful lightweight open-source cross-platform API Client
group: Applications/
vendor: potatosalad775
packager: potatosalad775
packagerEmail: transaction@kakao.com
license:
url: https://github.com/potatosalad775/eqTrainer

build_arch: x86_64, aarch64

# See the deb make_config: ALSA for flutter_soloud, GStreamer for
# audio_decoder.
requires:
  - alsa-lib
  - gstreamer1
  - gstreamer1-plugins-base
  - gstreamer1-plugins-good

keywords:
  - eq
  - eqTrainer

generic_name: Music Application

categories:
  - Music
  - Media

startup_notify: true