// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:eq_trainer/shared/model/audio_clip.dart';
import 'package:eq_trainer/shared/model/setting_data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AudioClipAdapter());
    registerAdapter(BackendDataAdapter());
    registerAdapter(MiscSettingsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AudioClipAdapter());
    registerAdapter(BackendDataAdapter());
    registerAdapter(MiscSettingsAdapter());
  }
}
